spring:
  application:
    name: guardian-api

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/guardian_db
    username: guardian_user
    password: guardian_pass
    driver-class-name: org.postgresql.Driver

  redis:
    host: localhost
    port: 6379
    timeout: 60000ms

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /api
  port: 8080

logging:
  level:
    root: INFO
    com.nevvesdev.guardianapi: DEBUG